name: Copy [linux-app] build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' #24:00(0:00)
    # - cron: '0 3 * * *' #12:00

jobs:
  Main-Program:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: Hebimalu0000/linux-app
        ref: build
        path: checkouted

    - name: Copy and Delete
      run: |
        tree checkouted/
        sudo cp -r checkouted/. public/
        tree public/
        sudo rm -rf checkouted

    - name: Commit and push changes
      run: |
        sudo git config user.name "auto-push"
        sudo git config user.email "auto-push@example.com"
        sudo git add .
        sudo git commit -m "auto push from ci" || echo "No changes to commit"
        sudo git push
