# This is a basic workflow that is manually triggered

name: Copy [linux-app] build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' #24:00(0:00)
    # - cron: '0 3 * * *' #12:00

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: Hebimalu0000/linux-app
        ref: build
        path: checkouted

    - name: Copy and Delete
      run: |
        sudo cp -r checkouted/. public/
        sudo rm -rf checkouted

    - name: Commit and push changes
      run: |
        git config user.name "auto-push"
        git config user.email "auto-push@example.com"
        git add .
        git commit -m "auto push from ci" || echo "No changes to commit"
        git push
