name: Package Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Package'
        required: true
      command:
        description: 'Command'
        required: true

jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run Test
        run: |
          sudo cat /etc/apt/apt-mirrors.txt
          sudo sh -c 'echo "http://apt.package-hebimalu0000.f5.si	priority:4" > /etc/apt/apt-mirrors.txt'
          sudo cat /etc/apt/apt-mirrors.txt
          sudo apt update
          sudo apt install ${{ github.event.inputs.name }}
          ${{ github.event.inputs.command }}
          
          
